### ISSUE TITLE
Hakemus-controllerin refaktorointi

### ISSUE THREAD

**Issue by rikukissa** [solita/livijuku-front#12]
Tämän [switchin](https://github.com/solita/livijuku-front/blob/develop/app/scripts/controllers/yhteinen/hakemus.js#L258-L274) ja funktion [kutsut](https://github.com/solita/livijuku-front/blob/develop/app/scripts/views/hakija/hakemus.html#L356) voisi korvata vaikka jakamalla switchin eri haarat omiksi funktioikseen ja syöttämällä funktiot sitten kutsuissa tallennaHakemus funktiolle parametrinä. Tällä hetkellä templatesta ei käy oikein ilmi, mitä funktio tekee eri numeroparametreillä. Vielä parempi olisi tehdä yksi funktio *tallennaHakemus* ja useampi funktio,  jotka ensin kutsuu tuota funktiota ja tekee sitten lisätoiminnon. 

Esimerkiksi tuo `tallennaHakemus(1)` case voisi olla jotain tyyliin: 

```javascript
$scope.naytaHakemus = function(tila) { 
  const ikkuna = $window.open('about:blank', '_blank');
  tallennaHakemus($scope.hakemus).then((hakemus) => {
    ikkuna.location.href = pdf.getHakemusPdfUrl(hakemus.id);
  })
}
```

Muutin esimerkissä myös tallennaHakemus funktion muotoon, jossa se ottaa tallennettavan hakemuksen parametrinä sisään. Funktiot yleisesti ottaen pysyy helpommin testattavina ja järkeiltävinä, jos niiden lopputulos ei riipu niiden ulkopuolella olevista tekijöistä. Jos funktio on yli 15 riviä pitkä, niin kannattaa alkaa harkitsemaan, voisiko sen jakaa useammaksi funktioksi.

Jos **if**-lauseen toinen haara on huomattavasti lyhyempi kuin ensimmäinen, kannattaa se siirtää ensimmäiseksi ja kääntää if-lauseen ehto. Tälläisissä funktiota "guardaavissa" if-lauseissa voi harkita myös seuraavanlaista patternia

Esimerkkinä tämä tapaus:
```javascript
$scope.tallennaHakemus = function (lisatoiminto) {
  StatusService.tyhjenna();
  $scope.$broadcast('show-errors-check-validity');

  if (ehto) {

    /*
     * 
     * 
     * Paljon koodia täällä
     * 
     * 
     */

  } else {
    $('input.ng-invalid').focus();
    StatusService.virhe('AvustuskohdeService.tallenna()', 'Korjaa lomakkeen virheet ennen tallentamista.');
  }
};
```

Kannattaisi muuttaa tähän muotoon

```javascript
$scope.tallennaHakemus = function (lisatoiminto) {
  StatusService.tyhjenna();
  $scope.$broadcast('show-errors-check-validity');

  if(!ehto) {    
    $('input.ng-invalid').focus();
    StatusService.virhe('AvustuskohdeService.tallenna()', 'Korjaa lomakkeen virheet ennen tallentamista.');
    return;
  }

  /*
   * 
   * 
   * Paljon koodia täällä
   * 
   * 
   */

};
```

Näin koko funktion vartaloa ei tarvi kääriä if-lauseeseen, säästytään yhdeltä sisennystasolta ja funktion luettavuus paranee.

**Comment by rikukissa** [comment]
https://github.com/airbnb/javascript
Tuolta löytyy hyviä vinkkejä koodin tyyliin yleisesti

**Comment by jegranbacka** [comment]
Kiitos vinkistä, näytti hyviltä koodausohjeilta
